README.md

- fixing Github workflow badge
- editing technical roadmap

docs: Fixed readme badge

---

.flake8
.github/workflows/doc-deploy.yaml
.github/workflows/documentation.yaml
.github/workflows/gh-page.yaml
.github/workflows/main.yml
.github/workflows/pypi-publish.yaml

- adding a documentation deployment workflow
- adding a GH page status workflow
- adding a pypi publish workflow
- enabling cache for python package dependencies

chore: Workflow update

---

.github/workflows/doc-deploy.yaml
.github/workflows/main.yml

- fixing the documentation deployment workflow

chore: Fixed documentation deployment

---

.github/workflows/doc-deploy.yaml
setup.py
torchscan/utils.py

docs: Fixed jekyll build

---

test/test_crawler.py
test/test_modules.py
test/test_process.py
test/test_utils.py
torchscan/crawler.py
torchscan/modules/flops.py
torchscan/modules/macs.py
torchscan/modules/memory.py
torchscan/utils.py

- fixing adaptive pooling statistics estimation
- adding unittests for uncovered modules

test: Added multiple unit tests for uncovered modules

---

README.md
test/test_modules.py
torchscan/modules/flops.py
torchscan/modules/macs.py
torchscan/modules/memory.py

This PR aims at :
- adding ops estimation support for `torch.nn.Identity` and Transposed convolutions
- adding corresponding tests

feat: Added module support

---

.github/workflows/pypi-publish.yaml

- fixing pypi publish workflow

chore: Fixed pypi-publish workflow

---

.gitignore
README.md
conda/meta.yaml
setup.py
torchscan/modules/memory.py

- updating the package version
- adding a first draft for conda recipe

chore: Post release updates

---

.github/workflows/main.yml
docs/source/conf.py
torchscan/utils.py

This PR adds Google analytics ID to verify website for Google search referencing

docs: Added website referencing

---

test/test_crawler.py
test/test_modules.py
test/test_process.py
test/test_utils.py
torchscan/crawler.py
torchscan/modules/flops.py
torchscan/modules/macs.py
torchscan/modules/memory.py
torchscan/process/memory.py
torchscan/utils.py

This PR cleans project files' headers by:
- removing shebang from non-script files
- adding encoding in unittests

style: Cleaned library headers

---

README.md
docs/source/modules.rst
torchscan/crawler.py

This PR documents the experimental feature of receptive field estimation.

docs: Updated readme and documentation

---

.github/workflows/pkg-publish.yaml
README.md
setup.py

This PR updates the readme and the conda upload job for the upcoming release.

chore: Updated jobs for release

---

.github/workflows/main.yml

This PR fixes the coverage upload to codecov

fix: Fixed codecov upload

---

.github/workflows/doc-deploy.yaml
.github/workflows/main.yml
.github/workflows/pkg-publish.yaml
mypy.ini
torchscan/crawler.py
torchscan/modules/__init__.py
torchscan/modules/flops.py
torchscan/modules/macs.py
torchscan/modules/memory.py
torchscan/modules/receptive.py
torchscan/process/__init__.py
torchscan/process/memory.py
torchscan/utils.py

This adds annotation typing to the codebase and a related mypy CI job to close #29

chore: Added annotation typing

---

torchscan/crawler.py
torchscan/utils.py

Correctly switch receptive field computation order to close #27.

feat: Switched correctly the RF computation order

---

README.md

This PR simply fixes the codacy badge URL

docs: Fixed codacy badge in README

---

CONTRIBUTING.md
README.md

- revamped README
- added citation example in README
- added missing sections in CONTRIBUTING

docs: Revamped README and updated CONTRIBUTING

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/builds.yml
.github/workflows/docs.yml
.github/workflows/pr-labels.yml
.github/workflows/style.yml
.github/workflows/tests.yml
CONTRIBUTING.md
README.md

This PR renames all ref to the master branch, into refs to main branch.

docs: Renamed ref from master to main

---

.github/workflows/style.yml
Makefile
pyproject.toml

- fixed pyproject.toml for mypy & isort
- updates CI jobs and Makefile
- fixed isort for api

style: Updated mypy and isort configs

---

.conda/meta.yaml
.flake8
docs/source/conf.py
pyproject.toml
torchscan/modules/flops.py

- updates the flake8 config
- Fixed the GH button
- Made the version specifiers stricter
- Fixed conda recipe

chore: Improved version specifiers and fixed conda recipe

---

.github/FUNDING.yml
.github/workflows/release.yml

This PR adds a sponsor button to the repository.

ci: Added FUNDING button

---

docs/build.sh

This PR cleans up the documentation build script

docs: Improved documentation build script

---

docs/source/index.rst

This PR adds the list of supported layers to the documentation.

docs: Added list of supported layers to documentation

---

.conda/meta.yaml
.github/workflows/release.yml

This PR fixes the release job and conda recipe for the upcoming release!

fix: Fixed release job and conda recipe

---

.github/workflows/release.yml
README.md
docs/build.sh
docs/source/_static/js/custom.js
docs/source/changelog.rst
setup.py

- adds anaconda badge to the readme
- updates the documentation
- updates version index
- updates CI release job

chore: Applied post-release modifications

---

.github/labeler.yml
.github/workflows/pull_requests.yml
.github/workflows/tests.yml
README.md

- fixes ref to CONTRIBUTING in the README
- adds missing installation step in CONTRIBUTING
- updates the labeler

docs: Updates README & CONTRIBUTING

---

.github/workflows/docs.yml

This PR fixes a typo to deploy the docs

ci(docs): fix typo in action for doc deploy

---

pyproject.toml

This PR fixes the non uniform definition of dev deps versioning

build(deps): fix inconsistency in deps versioning
